### ISSUE TITLE
Show "breadcrumbs" in web view

### ISSUE THREAD

**Issue by jwodder** [dandi/dandidav#14]
When viewing a collection as HTML, the request path should be shown above the table, and each component of the path should be a link back to that point in the path.

- The path should begin with a `dandidav` component that links to the root of the WebDAV hierarchy.

**Comment by yarikoptic** [comment]
I would have loved such a feature quite a bit since I wanted it a number of times already while navigating.
FWIW on datasets.datalad.org we use coloring in breadcrumbs to distinguish "root of git repo" (greenish blue?), "root of git annex repo" (orange), "path within" (blue) e.g. on https://datasets.datalad.org/?dir=/dandi/dandisets/000003/sub-YutaMouse20 
![image](https://github.com/dandi/dandidav/assets/39889/c6dd7679-c39f-4e9a-8251-9e5e85d769e4)

Here could be different colors for "meta path" components (all the `/dandisets/`, caching subfolders), ids (like dandiset or zarr id), versions (draft etc), and then path within, and zarr folder.   At least, if known, would be worth adding different styles in html and then let css customize if desired
